.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "DIRENV\-DIFF" "1" "December 2011" "0x2a" "direnv"
.
.SH "NAME"
\fBdirenv\-diff\fR \- Diff of ENVs
.
.SH "SYNOPSIS"
\fBdirenv diff [options] <OLD_ENV>\fR
.
.SH "DESCRIPTION"
This command is part of the porcelain, you usually don\'t use it direclty\.
.
.P
Echoes the difference between your ENV and the given compressed OLD_ENV\. See direnv\-dump(1) on how to produce a ENV dump\.
.
.IP "\(bu" 4
\-r outputs the reverse diff
.
.IP "" 0
.
.SH "SEE ALSO"
direnv(1), direnv\-dump(1)
