linters:
  presets:
    - bugs
    - unused
  enable:
    - gofmt
    - misspell
    - revive
    - stylecheck
  disable:
    # direnv is not a web server, context is not strictly necessary.
    - noctx
