queue_rules:
  - name: default
    queue_conditions:
      - base=master
      - label~=merge-queue|dependencies
    merge_conditions:
      - check-success=Analyze (go)
      - check-success=Go Build (macos-latest)
      - check-success=Go Build (ubuntu-latest)
      - check-success=Go Build (windows-latest)
      - check-success=Nix Build (macos-latest)
      - check-success=Nix Build (ubuntu-latest)
    merge_method: rebase

pull_request_rules:
  - name: refactored queue action rule
    conditions: []
    actions:
      queue:
