theme: jekyll-theme-primer
title: direnv
description: "unclutter your .profile"
url: "https://direnv.net"

exclude:
  - test

# see https://github.com/github/pages-gem/blob/754a725e4766d4329bb1dd0e07c638a045ad2c04/lib/github-pages/plugins.rb#L6-L42
plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-mentions
  - jekyll-readme-index
  - jekyll-sitemap

markdown: CommonMarkGhPages
# see https://github.com/gjtorikian/commonmarker#parse-options
commonmark:
  options:
    - FOOTNOTES
    - SMART
  extensions:
    - autolink
    - strikethrough
    - table
