package main

//nolint
const (
	DIRENV_CONFIG = "DIRENV_CONFIG"
	DIRENV_BASH   = "DIRENV_BASH"
	DIRENV_DEBUG  = "DIRENV_DEBUG"

	DIRENV_DIFF    = "DIRENV_DIFF"
	DIRENV_DIR     = "DIRENV_DIR"
	DIRENV_RC_FILE = "DIRENV_RC_FILE"
	DIRENV_WATCHES = "DIRENV_WATCHES"
)
