package main

const (
	DIRENV_CONFIG = "DIRENV_CONFIG"
	DIRENV_BASH   = "DIRENV_BASH"
	DIRENV_DEBUG  = "DIRENV_DEBUG"

	DIRENV_DIR = "DIRENV_DIR"
	// DIRENV_IN_ENVRC is only set in the context of the .envrc evaluation
	DIRENV_IN_ENVRC = "DIRENV_IN_ENVRC"
	DIRENV_WATCHES  = "DIRENV_WATCHES"
	DIRENV_DIFF     = "DIRENV_DIFF"
)
