package main

const (
	DIRENV_CONFIG = "DIRENV_CONFIG"
	DIRENV_BASH   = "DIRENV_BASH"

	DIRENV_DIR     = "DIRENV_DIR"
	DIRENV_MTIME   = "DIRENV_MTIME"
	DIRENV_WATCHES = "DIRENV_WATCHES"
	DIRENV_DIFF    = "DIRENV_DIFF"
)
