schema = 3

[mod]
  [mod.'github.com/BurntSushi/toml']
    version = 'v1.6.0'
    hash = 'sha256-ptdUJvuc21ixeLt+M5way/na3aCnCO4MYHWulWp8NEY='

  [mod.'github.com/mattn/go-isatty']
    version = 'v0.0.24'
    hash = 'sha256-pmq8KKIb2+qMF3E1cR2B7NAj5joF2tZduyXjIfIlkTk='

  [mod.'golang.org/x/mod']
    version = 'v0.41.0'
    hash = 'sha256-euzxa6DC2qmU+LgEwjOM71nc/lRrU9XRC9nESAaDw6Q='

  [mod.'golang.org/x/sys']
    version = 'v0.48.0'
    hash = 'sha256-u+LwI76YIeg1asQKZItD2mnL4Yvx8veLhBuL8wv60Ls='
