#!/usr/bin/env bash
# vim: ft=ruby
#
# Tools to backup the current environment
=begin 2>/dev/null
if ! [ -z "$RUBYOPT" ]; then
  export DIRENV_RUBYOPT="$RUBYOPT"
  unset RUBYOPT
fi
exec ${DIRENV_RUBY:-ruby} -e"\$0='$0'; load '$0'" -- $@
=end
ENV['RUBYOPT'] = ENV.delete 'DIRENV_RUBYOPT'

require 'zlib'
require 'base64'

# Don't backup unused variables
env = ENV.to_hash
%w{_ PWD OLDPWD SHLVL SHELL DIRENV_BACKUP DIRENV_LIBEXEC DIRENV_CONFIG_DIR DIRENV_DEBUG}.each do |var|
  env.delete(var)
end

puts Base64.encode64(
  Zlib::Deflate.deflate(
    Marshal.dump(env), Zlib::BEST_COMPRESSION
  )
).gsub("\n",'')
