#!/usr/bin/env bash
#
# Prints the target-shell hooks so that you don't have to update them
# if they change over time.
#

set -e

target=$1

# Linux shell auto-detection
if [ -z "$target" ] && [ -n "$PPID" ] && [ -f "/proc/$PPID/cmdline" ]; then
  target=`cat /proc/$PPID/cmdline`
  target=`basename "$target"`
fi

if [ -z "$target" ]; then
  echo "Please specify the target shell" >&2
  echo "usage: direnv hook \$0" >&2
  exit 1
fi

target=${target#-}
target=`basename "$target"`

# More of them here: http://www.linux.org/docs/ldp/howto/Xterm-Title-4.html
case "$target" in
bash)
  cat <<HOOK
PROMPT_COMMAND="eval \\\`$DIRENV_LIBEXEC/direnv-export\\\`;\$PROMPT_COMMAND"
HOOK
  ;;
zsh)
  cat <<HOOK
globsubst=\`setopt | grep globsubst\`;
unsetopt globsubst;
direnv_hook() {
  eval \`$DIRENV_LIBEXEC/direnv-export\`
};
[[ -z \$precmd_functions ]] && precmd_functions=();
precmd_functions=(\$precmd_functions direnv_hook);
[[ -n \$globsubst ]] && setopt globsubst
HOOK
  ;;
*)
    echo "Unknown target shell '$target'" >&2
    exit 1
esac
