#!/usr/bin/env bash
#
# git-like libexec switcher

set -e

usage() {
  echo "direnv enable|list-enabled|disable|export|exec|switch [options]" >&2
}

readlink=$(type -p greadlink readlink | head -1)

# usage: abs_dirname $filename
# finds the original $filename path and prints it's absolute folder path
abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  # Resolve the symlink(s) recursively
  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$($readlink "$name" || true)"
  done

  # prints an absolute path here
  pwd
  cd "$cwd"
}

if [ -z "$DIRENV_LIBEXEC" ]; then
  export DIRENV_LIBEXEC=$(abs_dirname "$0")
fi

if [ -z "$1" ]; then
  usage
  exit 1
fi

prefix="$DIRENV_LIBEXEC/direnv-"

if ! [ -x "$prefix$1" ]; then
  prefix="direnv-"
fi

exec $prefix$@
