#! /usr/bin/env bash

# Catch bugs
set -e -u

# load the stdlib
if [ -z "${DIRENV_LIBEXEC}" ]; then export DIRENV_LIBEXEC=$(dirname $0); fi
. "$DIRENV_LIBEXEC/direnv-stdlib" >&2

cat ${DIRENV_CONFIG_DIR}/sums/* | sort -u
