#!/bin/bash
=begin 2>/dev/null
if ! [ -z "$RUBYOPT" ]; then
  export DIRENV_RUBYOPT="$RUBYOPT"
  unset RUBYOPT
fi
exec ${DIRENV_RUBY:-ruby} -e"\$0='$0'; load '$0'" -- $@
=end
ENV['RUBYOPT'] = ENV.delete 'DIRENV_RUBYOPT'

require 'zlib'
require 'base64'

puts Base64.encode64(
  Zlib::Deflate.deflate(
    Marshal.dump(ENV.to_hash), Zlib::BEST_COMPRESSION
  )
).gsub("\n",'')
